tap "homebrew/bundle"
tap "homebrew/core"
brew "fish"
brew "fzf"
brew "ghq"
brew "gibo"
brew "goenv"
brew "hub"
brew "lua"
brew "nodebrew"
brew "rbenv"
brew "rmtrash"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vim", args: ["with-lua"]
